- name: Installing MySQL Libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop: 
  - PyMySQL
  - cryptography
- name: Installing MySQL Server
  ansible.builtin.package:
    name: mysql-server
    state: installed
- name: Starting MySQL Service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: Connect to MySQL Server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ lookup('amazon.aws.aws_ssm','/expense/mysql/mysql_root_password', decrypt=True) }}"
    login_host: mysql.sridevsecops.store
  register: mysql_info
  ignore_errors: yes

- name: Print the output
  ansible.builtin.debug:
    msg: "MySQL Server Info: {{ mysql_info }}"

- name: Set Up the Root Password
  ansible.builtin.command: mysql_secure_installation --set-root-pass 'ExpenseApp@1'
  when: mysql_info.failed is true