- name: removing exisitng directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION}}"
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION}}"
    state: directory

- name: Downloading the code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCATION }}"
    remote_src: yes